apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasha-k8s-dp
  labels:
    app: dasha-k8s-dp
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: kuber-app
        image: daryakokoreva/project_otus:latest
        ports:
        - containerPort: 8000   
        livenessProbe:
          httpGet:
            port: 8000
            path: /health/
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2   