apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usercrud-k8s-ig
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: usercrud-k8s-sv
            port:
              number: 80